# -*- coding: utf-8 -*-
"""zomato.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16mD7fE62tC2ZsdO_xGhDRBBxEDmjBZRK
"""

import pandas as pd

df=pd.read_csv('/content/zomato.csv.zip')

df.head()

df.isnull().sum()

df.info()

"""### Data Cleaning"""

print(f"Initial shape: {df.shape}")
df.drop_duplicates(inplace=True)
print(f"Shape after dropping duplicates: {df.shape}")

"""Let's handle missing values and data type conversions for critical columns."""

# Drop columns with many missing values or less relevance
df.drop(columns=['dish_liked', 'phone', 'address'], inplace=True)
print(f"Shape after dropping irrelevant columns: {df.shape}")

"""### Cleaning 'rate' column"""

df['rate'].unique()
# Remove '/5' and 'New' from 'rate' column and convert to numeric
df['rate'] = df['rate'].astype(str).str.replace('/5', '').str.replace('New', '0').str.replace(' ', '')
# Convert to numeric, coercing errors to NaN
df['rate'] = pd.to_numeric(df['rate'], errors='coerce')

# Fill missing values in 'rate' with the mean
df['rate'].fillna(df['rate'].mean(), inplace=True)
print(f"'rate' column unique values after cleaning: {df['rate'].unique()}")
df.isnull().sum()

"""### Cleaning 'approx_cost(for two people)' column"""

df['approx_cost(for two people)'].unique()
# Remove commas and convert to numeric
df['approx_cost(for two people)'] = df['approx_cost(for two people)'].astype(str).str.replace(',', '')
df['approx_cost(for two people)'] = pd.to_numeric(df['approx_cost(for two people)'], errors='coerce')

# Fill missing values with the mean
df['approx_cost(for two people)'].fillna(df['approx_cost(for two people)'].mean(), inplace=True)
print(f"'approx_cost(for two people)' column unique values after cleaning: {df['approx_cost(for two people)'].unique()}")
df.isnull().sum()

"""### Handling 'online_order' and 'book_table'"""

# Fill missing values with the mode
df['online_order'].fillna(df['online_order'].mode()[0], inplace=True)
df['book_table'].fillna(df['book_table'].mode()[0], inplace=True)
df.isnull().sum()

"""### Handling 'rest_type', 'cuisines', 'location', 'name', 'listed_in(type)'"""

# Fill missing values in categorical columns with their mode
for col in ['rest_type', 'cuisines', 'location', 'listed_in(type)']:
    df[col].fillna(df[col].mode()[0], inplace=True)

# Drop rows where 'name' is missing, as it's a critical identifier
df.dropna(subset=['name'], inplace=True)

df.isnull().sum()

"""### Cleaning 'votes' column"""

# Convert 'votes' to numeric, coercing errors to NaN
df['votes'] = pd.to_numeric(df['votes'], errors='coerce')

# Fill missing values in 'votes' with the mean
df['votes'].fillna(df['votes'].mean(), inplace=True)
df.isnull().sum()

"""### Final check of data types and null values after cleaning"""

df.info()
df.head()

"""## Data Exploration: Relationships between Features

### Cuisine vs. Rating
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate the average rating for each cuisine
cui_rating = df.groupby('cuisines')['rate'].mean().sort_values(ascending=False).head(10)

plt.figure(figsize=(12, 7))
sns.barplot(x=cui_rating.values, y=cui_rating.index, palette='viridis')
plt.title('Top 10 Cuisines by Average Rating')
plt.xlabel('Average Rating')
plt.ylabel('Cuisine')
plt.tight_layout()
plt.show()

"""### Location Hotspots"""

# Calculate the number of restaurants in each location
loc_counts = df['location'].value_counts().head(10)

plt.figure(figsize=(12, 7))
sns.barplot(x=loc_counts.values, y=loc_counts.index, palette='magma')
plt.title('Top 10 Locations by Number of Restaurants')
plt.xlabel('Number of Restaurants')
plt.ylabel('Location')
plt.tight_layout()
plt.show()

"""### Price vs. Rating"""

plt.figure(figsize=(12, 7))
sns.scatterplot(x='approx_cost(for two people)', y='rate', data=df, alpha=0.6, hue='online_order', palette='coolwarm')
plt.title('Restaurant Price (for two people) vs. Rating')
plt.xlabel('Approximate Cost (for two people)')
plt.ylabel('Rating')
plt.tight_layout()
plt.show()

"""### Correlation Heatmap of Numerical Features"""

numeric_df = df[['rate', 'votes', 'approx_cost(for two people)']]
correlation_matrix = numeric_df.corr()

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap of Numerical Features')
plt.tight_layout()
plt.show()

"""### Wordcloud for Cuisines"""

!pip install wordcloud

from wordcloud import WordCloud

# Join all cuisines into a single string, handling potential NaN values gracefully
all_cuisines = ' '.join(df['cuisines'].dropna().astype(str))

# Generate a word cloud image
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(all_cuisines)

# Display the generated image:
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud of Cuisines')
plt.show()







